### ISSUE TITLE
长链接没有认证校验，如果我调用接口，我可以直接获取群聊信息。

### ISSUE THREAD

**Issue by CoderXueXue** [zongzibinbin/MallChat#15]
<img width="1057" alt="image" src="https://github.com/zongzibinbin/MallChat/assets/63384492/f4e4650f-eabd-48af-b200-88ff0dabc109">

**Comment by CoderXueXue** [comment]
有人要写吗，没人写我就写了

**Comment by zongzibinbin** [comment]
我们默认就是支持未登录用户请求的呀。这算是一种产品设计，等到之后可能才会考虑只让登陆用户看到推送，别急着改哈

**Comment by CoderXueXue** [comment]
好吧
