### ISSUE TITLE
使用了SpringCache的相关注解,但是并没有在启动类添加@EnableCaching

### ISSUE THREAD

**Issue by hjxixi** [zongzibinbin/MallChat#181]
没有本地部署,单纯研究源码,在UserCache这个类中,你使用了@Cacheable注解,但是在启动类中并没有写@EnableCaching,也就是说@Cacheable是不起效果的,所有用到SpringCache注解的地方都无法生效

**Comment by Ershi-Gu** [comment]
在配置类CacheConfig中开启了

**Comment by hjxixi** [comment]
感谢解答，我还在学习阶段，第一次了解到这类注解可以写在非启动类里面
