### ISSUE TITLE
TextMsgHandler中自动装配规范问题

### ISSUE THREAD

**Issue by Yancyji** [zongzibinbin/MallChat#38]
static 成员不应该使用Autowired注解装配；既然使用了new 创建对象就不该再使用自动装配功能，且会找不到PrioritizedUrlTitleDiscover类型的bean对象
![image](https://github.com/zongzibinbin/MallChat/assets/43696248/342ad429-6575-47ee-99e4-641fee6c3be7)

**Comment by zongzibinbin** [comment]
不应该用Autowired，这个应该是误操作，可以提交个pr帮忙改一下
