### ISSUE TITLE
敏感词优化功能【招募】

### ISSUE THREAD

**Issue by zongzibinbin** [zongzibinbin/MallChat#41]
抹茶项目的敏感词功能还需要优化，有兴趣的可以下方评论下。
1.异步构建前缀数，不要占用spring的启动流程
2.前缀树需要有结束节点，否则判断会出问题
3.前缀数用map构建，提高匹配速度，不要用arraylist。

**Comment by xiaocairush** [comment]
提了一个个pr, https://github.com/zongzibinbin/MallChat/pull/42
应该可以满足第2, 3点要求，没有测试服务启动后是否生效，仅通过了单元测试。

**Comment by xiaocairush** [comment]
不足之处：
1. 在启动的时候一次拉取所有的敏感词性能有些问题，可以批次拉取
2. 目前ACTrie不是一个线程安全的类，可以考虑将它的初始化方法修改为线程安全的类，目前先不做这方面的修改。

思考：每个汉字3字节，假设一条敏感词10字节，那么100条敏感词大约1KB, 预估1MB的内存空间话可以放下10w条数据。因此可以预估出来数据规模不大，另外算法复杂度也不高，性能瓶颈主要在io上。相比将ACTrie修改为线程安全的类，敏感词放在本地文件而不是数据库中的话，性能会有更大的提高。

**Comment by Yancyji** [comment]
关于异步构建前缀树，异步初始化spring bean吧，参考sofa boot的异步初始化，可以提升启动的速度

**Comment by zongzibinbin** [comment]
> 敏感词只加载一次，在数据库管理着方便，这个还好
