### ISSUE TITLE
关于撤回消息时，用户昵称丢失问题

### ISSUE THREAD

**Issue by Yancyji** [zongzibinbin/MallChat#49]
撤回消息的时候，不显示撤回该消息的用户昵称了
![image](https://github.com/zongzibinbin/MallChat/assets/43696248/df8d98ec-bd7a-4b13-877f-b1b72d1a4aa5)

**Comment by zongzibinbin** [comment]
这个是改版还在进行中，等前端自己管理用户信息库的时候，就ok了

**Comment by Yancyji** [comment]
好的，那我关一下

**Comment by Yancyji** [comment]
OK
