### ISSUE TITLE
徽章及其文字显示问题

### ISSUE THREAD

**Issue by Yancyji** [zongzibinbin/MallChat#52]
![image](https://github.com/zongzibinbin/MallChat/assets/43696248/26d0e182-4f06-48c1-9364-a8960a0fc75f)
徽章显示不出来了，只有鼠标移上去才会显示徽章的文字，这个时候下滑，徽章描述文字会超过主体，跑到外面去

**Comment by hakusai22** [comment]
<img width="671" alt="image" src="https://github.com/zongzibinbin/MallChat/assets/58761705/9ca9e06a-1bcb-46f2-9435-ece9b75ed84b">

确实 前端出bug了

**Comment by zongzibinbin** [comment]
去前端项目提交下issue，附带下复现方法，辛苦了
