### ISSUE TITLE
RequestInfo 信息绑定问题

### ISSUE THREAD

**Issue by FRookie** [zongzibinbin/MallChat#80]
<img width="595" alt="截屏2023-07-03 16 38 24" src="https://github.com/zongzibinbin/MallChat/assets/33781946/a37ac85f-ec03-4af1-ac91-3d377d3262a8">

这个地方为啥要把单个channel的信息绑定到eventloop线程呢？如果eventloop对应多个channel的话不就覆盖掉了吗？

**Comment by zongzibinbin** [comment]
是的，这里其实没必要，后续我会把这个上下文删了，直接靠channel的附件来绑定值
